databases:
  - name: flutter-backend-db
    plan: free
    user: flutter_user

services:

  # Web Service - Go Backend
  - type: web
    name: flutter-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: AUTO_MIGRATE
        value: true
      - key: DB_DRIVER
        value: postgres
      - key: DB_DSN
        fromDatabase:
          name: flutter-backend-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: flutter-backend-redis
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"

  # Grafana Alloy Service (Metrics Agent)
  - type: web
    name: grafana-alloy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.alloy
    envVars:
      - key: PROMETHEUS_URL
        sync: false
      - key: PROMETHEUS_USER
        sync: false
      - key: PROMETHEUS_API_KEY
        sync: false
      - key: SCRAPE_TARGET
        value: flutter-backend-ac58.onrender.com:443

  # Redis Cache
  - type: redis
    name: flutter-backend-redis
    region: frankfurt
    plan: free
    ipAllowList: [] # Allow internal connections only
