databases:
  - name: flutter-backend-db
    plan: free
    user: flutter_user

services:

  # Web Service - Go Backend
  - type: web
    name: flutter-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: AUTO_MIGRATE
        value: true
      - key: DB_DRIVER
        value: postgres
      - key: DB_DSN
        fromDatabase:
          name: flutter-backend-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"
      - key: PROMETHEUS_URL
        sync: false
      - key: PROMETHEUS_USER
        sync: false
      - key: PROMETHEUS_API_KEY
        sync: false
